// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService handles persisting and loading dashboard configurations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * DeleteDashboard removes a saved dashboard config.
 */
export function DeleteDashboard(name: string): $CancellablePromise<void> {
    return $Call.ByID(2774059171, name);
}

/**
 * ListDashboards returns the names of all saved dashboard configs.
 */
export function ListDashboards(): $CancellablePromise<string[]> {
    return $Call.ByID(2548475543).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadDashboard loads a dashboard configuration by name.
 */
export function LoadDashboard(name: string): $CancellablePromise<models$0.DashboardConfig> {
    return $Call.ByID(3505436954, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveDashboard persists a dashboard configuration.
 */
export function SaveDashboard(cfg: models$0.DashboardConfig): $CancellablePromise<void> {
    return $Call.ByID(254120537, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.DashboardConfig.createFrom;
