// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService handles SQL Server connections and schema discovery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Connect opens a connection to SQL Server using the provided config.
 */
export function Connect(config: models$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(2894062437, config);
}

/**
 * Disconnect closes the database connection.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1991975495);
}

/**
 * GetColumns retrieves all columns for a given table.
 */
export function GetColumns(schema: string, table: string): $CancellablePromise<models$0.ColumnInfo[]> {
    return $Call.ByID(2763745422, schema, table).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTables retrieves all user tables from the connected database.
 * Excludes system schemas (sys, INFORMATION_SCHEMA, cdc) and MS replication
 * tables that live in user databases but are managed by SQL Server.
 */
export function GetTables(): $CancellablePromise<models$0.TableInfo[]> {
    return $Call.ByID(1512099106).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsConnected returns whether there is an active connection.
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(1961382396);
}

// Private type creation functions
const $$createType0 = models$0.ColumnInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.TableInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
