// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GeneratorService orchestrates generating an ASP.NET Core dashboard project.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Generate writes the complete ASP.NET Core project to disk.
 */
export function Generate(cfg: models$0.DashboardConfig): $CancellablePromise<string> {
    return $Call.ByID(3108838160, cfg);
}
