// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectExporter handles zipping generated projects for download.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportToZip creates a zip archive of the generated project directory.
 * Returns the path to the created zip file.
 */
export function ExportToZip(projectDir: string): $CancellablePromise<string> {
    return $Call.ByID(2920448749, projectDir);
}

/**
 * GetProjectSize returns the total size of files in the project directory.
 */
export function GetProjectSize(projectDir: string): $CancellablePromise<number> {
    return $Call.ByID(76204365, projectDir);
}
