// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AggregationType defines how a metric is aggregated.
 */
export enum AggregationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AggNone = "none",
    AggSum = "sum",
    AggAvg = "avg",
    AggMin = "min",
    AggMax = "max",
    AggCount = "count",
};

/**
 * ColumnInfo represents a column within a database table.
 */
export class ColumnInfo {
    "name": string;
    "dataType": string;
    "isNullable": boolean;
    "maxLength": number;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("isNullable" in $$source)) {
            this["isNullable"] = false;
        }
        if (!("maxLength" in $$source)) {
            this["maxLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

/**
 * ConnectionConfig holds the SQL Server connection parameters.
 */
export class ConnectionConfig {
    "server": string;
    "port": number;
    "database": string;
    "username": string;
    "password": string;
    "connectionStringRaw": string;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("connectionStringRaw" in $$source)) {
            this["connectionStringRaw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

/**
 * DashboardConfig is the complete configuration for a generated dashboard.
 */
export class DashboardConfig {
    "name": string;
    "description": string;
    "connection": ConnectionConfig;
    "tableName": string;
    "timestampCol": string;
    "machineCol": string;
    "metrics": Metric[];
    "widgets": WidgetInstance[];
    "refreshSeconds": number;
    "outputPath": string;

    /** Creates a new DashboardConfig instance. */
    constructor($$source: Partial<DashboardConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("connection" in $$source)) {
            this["connection"] = (new ConnectionConfig());
        }
        if (!("tableName" in $$source)) {
            this["tableName"] = "";
        }
        if (!("timestampCol" in $$source)) {
            this["timestampCol"] = "";
        }
        if (!("machineCol" in $$source)) {
            this["machineCol"] = "";
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = [];
        }
        if (!("widgets" in $$source)) {
            this["widgets"] = [];
        }
        if (!("refreshSeconds" in $$source)) {
            this["refreshSeconds"] = 0;
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DashboardConfig {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField2_0($$parsedSource["connection"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        if ("widgets" in $$parsedSource) {
            $$parsedSource["widgets"] = $$createField7_0($$parsedSource["widgets"]);
        }
        return new DashboardConfig($$parsedSource as Partial<DashboardConfig>);
    }
}

/**
 * Metric defines a single measurable value mapped to a database column.
 */
export class Metric {
    "name": string;
    "description": string;
    "column": string;
    "aggregation": AggregationType;
    "unit": string;
    "dataType": string;

    /** Creates a new Metric instance. */
    constructor($$source: Partial<Metric> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("aggregation" in $$source)) {
            this["aggregation"] = AggregationType.$zero;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metric instance from a string or object.
     */
    static createFrom($$source: any = {}): Metric {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metric($$parsedSource as Partial<Metric>);
    }
}

/**
 * TableInfo represents a database table discovered from SQL Server.
 */
export class TableInfo {
    "schema": string;
    "name": string;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

/**
 * WidgetInstance is a configured widget placed on a dashboard.
 */
export class WidgetInstance {
    "id": string;
    "type": WidgetType;
    "title": string;
    "metricId": string;

    /**
     * grid columns
     */
    "width": number;

    /**
     * grid rows
     */
    "height": number;
    "config": { [_ in string]?: string };

    /** Creates a new WidgetInstance instance. */
    constructor($$source: Partial<WidgetInstance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = WidgetType.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("metricId" in $$source)) {
            this["metricId"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WidgetInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): WidgetInstance {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField6_0($$parsedSource["config"]);
        }
        return new WidgetInstance($$parsedSource as Partial<WidgetInstance>);
    }
}

/**
 * WidgetType represents the kind of dashboard widget.
 */
export enum WidgetType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WidgetTodayConsumption = "today_consumption",
    WidgetHourlyTrend = "hourly_trend",
    WidgetDailyTrend = "daily_trend",
    WidgetWeeklyComparison = "weekly_comparison",
    WidgetMonthlyTrend = "monthly_trend",
    WidgetMachineComparison = "machine_comparison",
    WidgetPieChart = "pie_chart",
    WidgetGauge = "gauge",
    WidgetDataTable = "data_table",
    WidgetKPI = "kpi",
    WidgetEfficiency = "efficiency",
    WidgetCost = "cost",
    WidgetForecast = "forecast",
};

// Private type creation functions
const $$createType0 = ConnectionConfig.createFrom;
const $$createType1 = Metric.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = WidgetInstance.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
