import { useState, useEffect } from 'react';
import type { AppStep, DashboardConfig } from './types';
import ConnectionPanel from './components/ConnectionPanel';
import SchemaExplorer from './components/SchemaExplorer';
import MetricMapper from './components/MetricMapper';
import WidgetPalette from './components/WidgetPalette';
import GeneratePanel from './components/GeneratePanel';
import { getAppVersion } from './hooks/useWails';
import './App.css';

const STEPS: { key: AppStep; label: string }[] = [
  { key: 'connect', label: 'Connect' },
  { key: 'schema', label: 'Schema' },
  { key: 'metrics', label: 'Metrics' },
  { key: 'widgets', label: 'Widgets' },
  { key: 'generate', label: 'Generate' },
];

const DEFAULT_CONFIG: DashboardConfig = {
  name: 'MyDashboard',
  description: 'Generated by Compozah',
  connection: { server: 'localhost', port: 1433, database: '', username: 'sa', password: '' },
  tableName: '',
  timestampCol: '',
  machineCol: '',
  metrics: [],
  widgets: [],
  refreshSeconds: 60,
  outputPath: './output',
};

function App() {
  const [step, setStep] = useState<AppStep>('connect');
  const [config, setConfig] = useState<DashboardConfig>(DEFAULT_CONFIG);
  const [version, setVersion] = useState('');

  useEffect(() => {
    getAppVersion().then(setVersion).catch(() => {});
  }, []);

  const currentIdx = STEPS.findIndex((s) => s.key === step);

  const goTo = (s: AppStep) => setStep(s);

  return (
    <div className="app-container">
      {/* Sidebar */}
      <aside className="sidebar">
        <div className="sidebar-brand">
          <img src="/logo.png" className="brand-logo" alt="" />
          <div className="brand-name">Compozah</div>
          <div className="brand-tagline">Low-code dashboard builder</div>
        </div>

        <nav className="step-nav">
          {STEPS.map((s, idx) => {
            const isActive = s.key === step;
            const isDone = idx < currentIdx;
            return (
              <button
                key={s.key}
                className={`step-nav-item ${isActive ? 'active' : ''} ${isDone ? 'done' : ''}`}
                onClick={() => goTo(s.key)}
                disabled={idx > currentIdx && !isDone}
              >
                <span className="step-num">{isDone ? '✓' : idx + 1}</span>
                <span className="step-label">{s.label}</span>
              </button>
            );
          })}
        </nav>

        <div className="sidebar-footer">
          <div className="config-summary">
            {config.tableName && (
              <div className="config-chip">{config.tableName}</div>
            )}
            {config.metrics.length > 0 && (
              <div className="config-chip">{config.metrics.length} metrics</div>
            )}
            {config.widgets.length > 0 && (
              <div className="config-chip">{config.widgets.length} widgets</div>
            )}
          </div>
          {version && <div className="app-version">v{version}</div>}
        </div>
      </aside>

      {/* Main content */}
      <main className="main-content">
        {step === 'connect' && (
          <ConnectionPanel
            config={config.connection}
            onChange={(conn) => setConfig({ ...config, connection: conn })}
            onConnected={() => goTo('schema')}
          />
        )}
        {step === 'schema' && (
          <SchemaExplorer
            config={config}
            onChange={setConfig}
            onNext={() => goTo('metrics')}
            onBack={() => goTo('connect')}
          />
        )}
        {step === 'metrics' && (
          <MetricMapper
            config={config}
            onChange={setConfig}
            onNext={() => goTo('widgets')}
            onBack={() => goTo('schema')}
          />
        )}
        {step === 'widgets' && (
          <WidgetPalette
            config={config}
            onChange={setConfig}
            onNext={() => goTo('generate')}
            onBack={() => goTo('metrics')}
          />
        )}
        {step === 'generate' && (
          <GeneratePanel
            config={config}
            onChange={setConfig}
            onBack={() => goTo('widgets')}
          />
        )}
      </main>
    </div>
  );
}

export default App;
