import { useState, useEffect, useRef, useCallback } from 'react';
import type { AppStep, DashboardConfig } from './types';
import ConnectionPanel from './components/ConnectionPanel';
import DataConfig from './components/DataConfig';
import WidgetPalette from './components/WidgetPalette';
import DashboardPreview from './components/DashboardPreview';
import GeneratePanel from './components/GeneratePanel';
import { getAppVersion, autoSave, loadAutoSave } from './hooks/useWails';
import './App.css';

const STEPS: { key: AppStep; label: string }[] = [
  { key: 'connect', label: 'Connect' },
  { key: 'data', label: 'Data' },
  { key: 'widgets', label: 'Widgets' },
  { key: 'preview', label: 'Preview' },
  { key: 'generate', label: 'Export' },
];

const DEFAULT_CONFIG: DashboardConfig = {
  name: 'MyDashboard',
  description: 'Generated by Compozah',
  connection: { server: 'localhost', port: 1433, database: '', username: 'sa', password: '', connectionStringRaw: '' },
  tableName: '',
  timestampCol: '',
  machineCol: '',
  metrics: [],
  widgets: [],
  refreshSeconds: 60,
  outputPath: './output',
};

function App() {
  const [step, setStep] = useState<AppStep>('connect');
  const [config, setConfig] = useState<DashboardConfig>(DEFAULT_CONFIG);
  const [version, setVersion] = useState('');
  const configRef = useRef(config);
  configRef.current = config;

  // Load autosave on startup.
  useEffect(() => {
    loadAutoSave().then((saved) => {
      if (saved && saved.connection) {
        setConfig(saved);
        // Jump to the last meaningful step.
        if (saved.widgets.length > 0) setStep('preview');
        else if (saved.metrics.length > 0) setStep('widgets');
        else if (saved.tableName) setStep('data');
      }
    }).catch(() => {});
    getAppVersion().then(setVersion).catch(() => {});
  }, []);

  // Auto-save on config change (debounced 2s).
  const saveTimer = useRef<ReturnType<typeof setTimeout>>(undefined);
  const debouncedSave = useCallback(() => {
    clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      autoSave(configRef.current).catch(() => {});
    }, 2000);
  }, []);

  useEffect(() => {
    if (config.tableName || config.metrics.length > 0 || config.widgets.length > 0) {
      debouncedSave();
    }
    return () => clearTimeout(saveTimer.current);
  }, [config, debouncedSave]);

  const currentIdx = STEPS.findIndex((s) => s.key === step);
  const goTo = (s: AppStep) => setStep(s);

  return (
    <div className="app-container">
      <aside className="sidebar">
        <div className="sidebar-brand">
          <img src="/logo.png" className="brand-logo" alt="" />
          <div className="brand-name">Compozah</div>
          <div className="brand-tagline">Low-code dashboard builder</div>
        </div>

        <nav className="step-nav">
          {STEPS.map((s, idx) => {
            const isActive = s.key === step;
            const isDone = idx < currentIdx;
            return (
              <button
                key={s.key}
                className={`step-nav-item ${isActive ? 'active' : ''} ${isDone ? 'done' : ''}`}
                onClick={() => goTo(s.key)}
                disabled={idx > currentIdx && !isDone}
              >
                <span className="step-num">{isDone ? '✓' : idx + 1}</span>
                <span className="step-label">{s.label}</span>
              </button>
            );
          })}
        </nav>

        <div className="sidebar-footer">
          <div className="config-summary">
            {config.tableName && <div className="config-chip">{config.tableName}</div>}
            {config.metrics.length > 0 && <div className="config-chip">{config.metrics.length} metrics</div>}
            {config.widgets.length > 0 && <div className="config-chip">{config.widgets.length} widgets</div>}
          </div>
          {version && <div className="app-version">v{version}</div>}
        </div>
      </aside>

      <main className="main-content">
        {step === 'connect' && (
          <ConnectionPanel
            config={config.connection}
            onChange={(conn) => setConfig({ ...config, connection: conn })}
            onConnected={() => goTo('data')}
          />
        )}
        {step === 'data' && (
          <DataConfig
            config={config}
            onChange={setConfig}
            onNext={() => goTo('widgets')}
            onBack={() => goTo('connect')}
          />
        )}
        {step === 'widgets' && (
          <WidgetPalette
            config={config}
            onChange={setConfig}
            onNext={() => goTo('preview')}
            onBack={() => goTo('data')}
          />
        )}
        {step === 'preview' && (
          <DashboardPreview
            config={config}
            onBack={() => goTo('widgets')}
            onNext={() => goTo('generate')}
          />
        )}
        {step === 'generate' && (
          <GeneratePanel
            config={config}
            onChange={setConfig}
            onBack={() => goTo('preview')}
          />
        )}
      </main>
    </div>
  );
}

export default App;

